language: cpp
compiler:
  - clang
  - gcc
matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
            - george-edison55-precise-backports
          packages:
            - clang-5.0
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
before_install:
    - eval "${MATRIX_EVAL}"

script: 
	- mkdir build 
	- cd build 
	- cmake .. 
	- make
