sudo: required
language: cpp
compiler:
  - clang
  - gcc
services:
  - docker
matrix:
  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
            - george-edison55-precise-backports
          packages:
            - clang-5.0
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
before_install:
  - eval "${MATRIX_EVAL}"
  - docker build -t boussau/alesuite:latest etc/filesDockerImage/

script:
  - docker run --rm boussau/alesuite:latest ALEobserve
