sudo: required
language: python
python:
  - 2.7
  - 3.5
  - 3.6
services:
  - docker
install:
  - docker build -t boussau/alesuite:latest etc/filesDockerImage/
  - docker run -d boussau/alesuite:latest --name alesuite ALEobserve
script:
  - docker ps | grep -q alesuite
